package io.livekit.sdk;

/** A chat message exchanged between participants. */
public class ChatMessage {
  private final String id;
  private final long timestamp;
  private final String message;
  private final Long editTimestamp;
  private final boolean deleted;
  private final boolean generated;

  public ChatMessage(
      String id,
      long timestamp,
      String message,
      Long editTimestamp,
      boolean deleted,
      boolean generated) {
    this.id = id;
    this.timestamp = timestamp;
    this.message = message;
    this.editTimestamp = editTimestamp;
    this.deleted = deleted;
    this.generated = generated;
  }

  public String getId() {
    return id;
  }

  public long getTimestamp() {
    return timestamp;
  }

  public String getMessage() {
    return message;
  }

  /** Set when this message is an edit of an earlier message with the same id. */
  public Long getEditTimestamp() {
    return editTimestamp;
  }

  public boolean isDeleted() {
    return deleted;
  }

  /** True if the message was generated by an agent from audio transcription. */
  public boolean isGenerated() {
    return generated;
  }

  public livekit.LivekitModels.ChatMessage toProto() {
    livekit.LivekitModels.ChatMessage.Builder builder =
        livekit.LivekitModels.ChatMessage.newBuilder()
            .setId(id)
            .setTimestamp(timestamp)
            .setMessage(message == null ? "" : message)
            .setDeleted(deleted)
            .setGenerated(generated);
    if (editTimestamp != null) {
      builder.setEditTimestamp(editTimestamp);
    }
    return builder.build();
  }

  public static ChatMessage fromProto(livekit.LivekitModels.ChatMessage proto) {
    return new ChatMessage(
        proto.getId(),
        proto.getTimestamp(),
        proto.getMessage(),
        proto.hasEditTimestamp() ? proto.getEditTimestamp() : null,
        proto.getDeleted(),
        proto.getGenerated());
  }
}
